language: node_js
node_js:
  - '8'
install:
  - npm install
  - npm install -g gulp-cli
script: gulp
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/  # or remove this line to upload from root of repo
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
